name: 'Build Client for Develop PR Prior to Merge'

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'closed'
    branches:
      - 'develop'

jobs:
  build-push-deploy:
    name: 'Build Client Prior to Merge'
    runs-on: ubuntu-latest
    if: ${{ (github.event.action != 'closed') }}

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # # gcloud CLI setup
    # - name: Login to GCP
    #   uses: google-github-actions/setup-gcloud@v0
    #   with:
    #     service_account_key: ${{ secrets.DEV_SA_KEY }}
    #     project_id: skyviewer
    #     export_default_credentials: true

    # # To prevent Cloud Build timeout, extend timeout deadline
    # - name: Extend Cloud Build timeout deadline
    #   run: gcloud config set app/cloud_build_timeout 2000
      
    # # The app.yaml is explicitly ignored in the .gitignore
    # - name: Create app.yaml
    #   run: touch app.yaml
    
    # - name: Get app.yaml
    #   run: gcloud secrets versions access latest --secret=alert-streaming-client-appyaml > app.yaml
    
    # # Build and push image to Google Container Registry
    # - name: Build
    #   run: |-
    #     gcloud builds submit \
    #       --quiet \
    #       --tag "us.gcr.io/skyviewer/alert-streaming-client:github-open-pr"
    - name: Setup docker build
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Build client, but don't deploy
      run: docker build . # will run buildx
